kind: pipeline
name: staging

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: golang
  commands:
  - go mod vendor
  - go build -mod vendor main.go
  - echo -n "app1" > .tags

- name: publish
  pull: always
  image: plugins/ecr
  settings:
    access_key:
      from_secret: AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    repo: 400856814742.dkr.ecr.us-east-2.amazonaws.com/app1
    registry: 400856814742.dkr.ecr.us-east-2.amazonaws.com
    region: us-east-2

- name: deployment
  image: imdglobalservices/drone-eks-plugin:latest
  settings:
    iam_role_arn: arn:aws:iam::400856814742:user/Carneles
    eks_cluster: sirs_tag
    repo: 400856814742.dkr.ecr.us-east-2.amazonaws.com/app1
    tag: app1
    namespace: default
    deployment: app-1
    container: app-1
    aws-region: us-east-2