kind: pipeline
name: staging

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: golang
  commands:
  - go mod vendor
  - go build -mod vendor main.go
  - echo -n "app1" > .tags

- name: publish
  pull: always
  image: plugins/ecr
  settings:
    access_key:
      from_secret: AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    repo: 400856814742.dkr.ecr.us-east-2.amazonaws.com/app1
    registry: 400856814742.dkr.ecr.us-east-2.amazonaws.com
    region: us-east-2

- name: deployment
  image: caian/drone-eks-plugin
  settings:
    access_key:
      from_secret: AWS_ACCESS_KEY_ID
    secret_key: 
      from_secret: AWS_SECRET_ACCESS_KEY
    cluster: arn:aws:eks:us-east-2:400856814742:cluster/sirs-stag
    node_role: arn:aws:iam::400856814742:role/eksctl-sirs-stag-cluster-ServiceRole-XVL3IPICVXIB
    manifest: k8s/deployment.yml
    aws_region: us-east-2