apiVersion: v1
kind: Service
metadata:
  name: app-1
  namespace: sirs
spec:
  type: LoadBalancer
  # type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: app-1