apiVersion: v1
kind: Service
metadata:
  name: app-1
  namespace: sirs
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
    external-dns.alpha.kubernetes.io/hostname: imdglobalservices.com
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ssl-cert-id
spec:
  type: LoadBalancer
  # type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: app-1